use super::RunnerCapabilityRequirement::{FileRead, SkillManagement, StructuredProcess};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, require_all_scopes, ToolDefinition,
    ToolOperatorExtensionFamily, TOOL_CATEGORY_RUNTIME,
};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{JobRun, Read, SkillManage},
    ADMIN, JOB_RUN, PROJECT_READ, TOOL_PROVIDER_RUNNER,
};
use crate::registry::input_schemas::{run_skill_resource_input_schema, skill_load_input_schema};

/// Project Skill runtime tools. `skill_load` is the narrow direct model path;
/// the broader discovery/read compatibility tools remain hidden operator
/// extensions. Kernel capability and authority gates remain authoritative.
pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    adaptive_runtime_direct(
        model_spec(
            def(
                "skill_load",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("catalog_revision"),
                    super::ToolAuditResultField::value("skill_id"),
                    super::ToolAuditResultField::value("name"),
                    super::ToolAuditResultField::value("source_scope"),
                    super::ToolAuditResultField::value("trust"),
                    super::ToolAuditResultField::value("package_revision"),
                    super::ToolAuditResultField::value("definition_revision"),
                    super::ToolAuditResultField::value("path"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .context(super::ToolAuditContextPolicy::Fields(&[
                    super::ToolAuditResultField::value("catalog_revision"),
                    super::ToolAuditResultField::value("skill_id"),
                    super::ToolAuditResultField::value("name"),
                    super::ToolAuditResultField::value("source_scope"),
                    super::ToolAuditResultField::value("trust"),
                    super::ToolAuditResultField::value("package_revision"),
                    super::ToolAuditResultField::value("definition_revision"),
                    super::ToolAuditResultField::value("path"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])),
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                Some(FileRead),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Load one uniquely named Skill by exact name using Unicode lowercase matching for an authorized Project. Returns the selected descriptor plus bounded SKILL.md text and revision metadata in one read-only call. Ambiguous names fail closed; scripts and other Skill resources are never executed.",
            skill_load_input_schema,
        ),
        27,
    ),
    adaptive_runtime_direct(
        require_all_scopes(
            model_spec(
                def(
                    "run_skill_resource",
                    super::ToolAuditPolicy::typed_fields(&[
                        super::ToolAuditResultField::value("skill_id"),
                        super::ToolAuditResultField::value("skill_name"),
                        super::ToolAuditResultField::value("skill_path"),
                        super::ToolAuditResultField::value("skill_sha256"),
                        super::ToolAuditResultField::value("skill_trust"),
                        super::ToolAuditResultField::value("skill_definition_revision"),
                        super::ToolAuditResultField::value("skill_package_revision"),
                        super::ToolAuditResultField::value("execution_state"),
                        super::ToolAuditResultField::value("exit_code"),
                        super::ToolAuditResultField::value("failure_kind"),
                        super::ToolAuditResultField::value("tool_failure"),
                    ])
                    .session_input(super::ToolAuditSessionInputPolicy::OmitTopLevel(&[
                        "args",
                        "process_summary",
                    ])),
                    ModelVisible,
                    TOOL_CATEGORY_RUNTIME,
                    Some(StructuredProcess),
                    TOOL_PROVIDER_RUNNER,
                    super::ToolSemanticContract {
                        effect: super::ToolEffect::Execute,
                        risk: JobRun,
                        approval: super::ToolApprovalPolicy::Standard,
                        idempotency: super::ToolIdempotency::NonIdempotent,
                    },
                    Some(JOB_RUN),
                    true,
                    NoPath,
                    true,
                    true,
                    super::ToolSessionEvidencePolicy::NONE,
                ),
                "Execute one trusted Runner-configured or Runner-installed Skill script without exposing or retransmitting its source through model context. Only supported scripts/ resources are executable. WebCodex selects the interpreter from the resource extension (.py or .sh), supplies the script over stdin, and appends only caller-provided script arguments after the interpreter's script marker. expected_definition_revision is mandatory; installed Skills also require expected_package_revision; project-content Skills are rejected.",
                run_skill_resource_input_schema,
            )
            .with_gpt_action_description("Execute one revision-fenced .py or .sh script from a trusted Runner Skill through a WebCodex-selected interpreter. Callers supply only script arguments; project-content Skills and unsupported resources are rejected, and the script body stays out of model arguments.")
            .with_execution(super::ToolExecutionContract::new(
                super::ToolExecutionForm::NativeArgv,
                super::ToolExecutionLifetime::Runner,
                super::ToolExecutionStart::SyncFirst,
                super::ToolExecutionContinuation::ObserveJobs,
            )),
            &[PROJECT_READ, JOB_RUN],
        ),
        71,
    ),
    def(
        "skill_list",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])
        .context(super::ToolAuditContextPolicy::Fields(&[
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillRuntime),
    def(
        "skill_read_file",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("source_scope"),
            super::ToolAuditResultField::value("trust"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])
        .context(super::ToolAuditContextPolicy::Fields(&[
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillRuntime),
    def(
        "skill_versions",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_install",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("artifact_sha256"),
            super::ToolAuditResultField::value("file_count"),
            super::ToolAuditResultField::value("total_bytes"),
            super::ToolAuditResultField::value("installed"),
            super::ToolAuditResultField::value("activated"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_activate",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("previous_active_package_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("changed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_remove_revision",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("removed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        true,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
];
