use super::RunnerCapabilityRequirement::{FileRead, SkillManagement};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, ToolDefinition, ToolOperatorExtensionFamily,
    TOOL_CATEGORY_RUNTIME,
};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{Read, SkillManage},
    ADMIN, PROJECT_READ, TOOL_PROVIDER_RUNNER,
};
use crate::registry::input_schemas::skill_load_input_schema;

/// Project Skill runtime tools. `skill_load` is the narrow direct model path;
/// the broader discovery/read compatibility tools remain hidden operator
/// extensions. Kernel capability and authority gates remain authoritative.
pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    adaptive_runtime_direct(
        model_spec(
            def(
                "skill_load",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("project"),
                    super::ToolAuditResultField::value("catalog_revision"),
                    super::ToolAuditResultField::value("skill_id"),
                    super::ToolAuditResultField::value("name"),
                    super::ToolAuditResultField::value("source_scope"),
                    super::ToolAuditResultField::value("trust"),
                    super::ToolAuditResultField::value("package_revision"),
                    super::ToolAuditResultField::value("definition_revision"),
                    super::ToolAuditResultField::value("path"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])
                .context(super::ToolAuditContextPolicy::Fields(&[
                    super::ToolAuditResultField::value("catalog_revision"),
                    super::ToolAuditResultField::value("skill_id"),
                    super::ToolAuditResultField::value("name"),
                    super::ToolAuditResultField::value("source_scope"),
                    super::ToolAuditResultField::value("trust"),
                    super::ToolAuditResultField::value("package_revision"),
                    super::ToolAuditResultField::value("definition_revision"),
                    super::ToolAuditResultField::value("path"),
                    super::ToolAuditResultField::value("sha256"),
                    super::ToolAuditResultField::value("returned_lines"),
                    super::ToolAuditResultField::value("has_more"),
                    super::ToolAuditResultField::value("next_start_line"),
                    super::ToolAuditResultField::value("candidate_count"),
                    super::ToolAuditResultField::value("error_kind"),
                    super::ToolAuditResultField::value("state_changed"),
                ])),
                ModelVisible,
                TOOL_CATEGORY_RUNTIME,
                Some(FileRead),
                TOOL_PROVIDER_RUNNER,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Load one uniquely named Skill by exact case-insensitive name for an authorized Project. Returns the selected descriptor plus bounded SKILL.md text and revision metadata in one read-only call. Ambiguous names fail closed; scripts and other Skill resources are never executed.",
            skill_load_input_schema,
        ),
        27,
    ),
    def(
        "skill_list",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])
        .context(super::ToolAuditContextPolicy::Fields(&[
            super::ToolAuditResultField::value("catalog_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("returned_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("truncated"),
            super::ToolAuditResultField::value("invalid_count"),
            super::ToolAuditResultField::value("discovery_truncated"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillRuntime),
    def(
        "skill_read_file",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("source_scope"),
            super::ToolAuditResultField::value("trust"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])
        .context(super::ToolAuditContextPolicy::Fields(&[
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("path"),
            super::ToolAuditResultField::value("sha256"),
            super::ToolAuditResultField::value("start_line"),
            super::ToolAuditResultField::value("end_line"),
            super::ToolAuditResultField::value("returned_lines"),
            super::ToolAuditResultField::value("has_more"),
            super::ToolAuditResultField::value("next_start_line"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ])),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(FileRead),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillRuntime),
    def(
        "skill_versions",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("total_count"),
            super::ToolAuditResultField::value("offset"),
            super::ToolAuditResultField::value("next_offset"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_install",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("definition_revision"),
            super::ToolAuditResultField::value("artifact_sha256"),
            super::ToolAuditResultField::value("file_count"),
            super::ToolAuditResultField::value("total_bytes"),
            super::ToolAuditResultField::value("installed"),
            super::ToolAuditResultField::value("activated"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_activate",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("previous_active_package_revision"),
            super::ToolAuditResultField::value("active_package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("changed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
    def(
        "skill_remove_revision",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("project"),
            super::ToolAuditResultField::value("skill_id"),
            super::ToolAuditResultField::value("skill_key"),
            super::ToolAuditResultField::value("package_revision"),
            super::ToolAuditResultField::value("state_revision"),
            super::ToolAuditResultField::value("removed"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("outcome_unknown"),
            super::ToolAuditResultField::value("error_kind"),
            super::ToolAuditResultField::value("state_changed"),
        ]),
        ModelHidden,
        TOOL_CATEGORY_RUNTIME,
        Some(SkillManagement),
        TOOL_PROVIDER_RUNNER,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: SkillManage,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(ADMIN),
        true,
        NoPath,
        true,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_operator_extension_family(ToolOperatorExtensionFamily::SkillManagement),
];
